name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q pytest tqdm
          pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -e .
      - name: Run tests with pytest
        run: pytest -s
